update ball_to_ball_data set batting_team = 'CSK' where batting_team = 'Chennai Super Kings';
        update ball_to_ball_data set batting_team = 'SRH' where batting_team = 'Sunrisers Hyderabad';
        update ball_to_ball_data set batting_team = 'LSG' where batting_team = 'Lucknow Super Giants';
        update ball_to_ball_data set batting_team = 'RR' where batting_team = 'Rajasthan Royals';
        update ball_to_ball_data set batting_team = 'PBKS' where batting_team = 'Punjab Kings';
        update ball_to_ball_data set batting_team = 'PBKS' where batting_team = 'Kings XI Punjab';
        update ball_to_ball_data set batting_team = 'RCB' where batting_team = 'Royal Challengers Bengaluru';
        update ball_to_ball_data set batting_team = 'RCB' where batting_team = 'Royal Challengers Bangalore';
        update ball_to_ball_data set batting_team = 'GT' where batting_team = 'Gujarat Titans';
        update ball_to_ball_data set batting_team = 'MI' where batting_team = 'Mumbai Indians';
        update ball_to_ball_data set batting_team = 'DC' where batting_team = 'Delhi Capitals';
        update ball_to_ball_data set batting_team = 'DC' where batting_team = 'Delhi Daredevils';
        update ball_to_ball_data set batting_team = 'KKR' where batting_team = 'Kolkata Knight Riders';

        update ball_to_ball_data set bowling_team = 'CSK' where bowling_team = 'Chennai Super Kings';
        update ball_to_ball_data set bowling_team = 'SRH' where bowling_team = 'Sunrisers Hyderabad';
        update ball_to_ball_data set bowling_team = 'LSG' where bowling_team = 'Lucknow Super Giants';
        update ball_to_ball_data set bowling_team = 'RR' where bowling_team = 'Rajasthan Royals';
        update ball_to_ball_data set bowling_team = 'PBKS' where bowling_team = 'Punjab Kings';
        update ball_to_ball_data set bowling_team = 'PBKS' where bowling_team = 'Kings XI Punjab';
        update ball_to_ball_data set bowling_team = 'RCB' where bowling_team = 'Royal Challengers Bengaluru';
        update ball_to_ball_data set bowling_team = 'RCB' where bowling_team = 'Royal Challengers Bangalore';
        update ball_to_ball_data set bowling_team = 'GT' where bowling_team = 'Gujarat Titans';
        update ball_to_ball_data set bowling_team = 'MI' where bowling_team = 'Mumbai Indians';
        update ball_to_ball_data set bowling_team = 'DC' where bowling_team = 'Delhi Capitals';
        update ball_to_ball_data set bowling_team = 'DC' where bowling_team = 'Delhi Daredevils';
        update ball_to_ball_data set bowling_team = 'KKR' where bowling_team = 'Kolkata Knight Riders';

        update matches set winner_team_name = 'CSK' where winner_team_name = 'Chennai Super Kings';
        update matches set winner_team_name = 'SRH' where winner_team_name = 'Sunrisers Hyderabad';
        update matches set winner_team_name = 'LSG' where winner_team_name = 'Lucknow Super Giants';
        update matches set winner_team_name = 'RR' where winner_team_name = 'Rajasthan Royals';
        update matches set winner_team_name = 'PBKS' where winner_team_name = 'Punjab Kings';
        update matches set winner_team_name = 'PBKS' where winner_team_name = 'Kings XI Punjab';
        update matches set winner_team_name = 'RCB' where winner_team_name = 'Royal Challengers Bengaluru';
        update matches set winner_team_name = 'RCB' where winner_team_name = 'Royal Challengers Bangalore';
        update matches set winner_team_name = 'GT' where winner_team_name = 'Gujarat Titans';
        update matches set winner_team_name = 'MI' where winner_team_name = 'Mumbai Indians';
        update matches set winner_team_name = 'DC' where winner_team_name = 'Delhi Capitals';
        update matches set winner_team_name = 'DC' where winner_team_name = 'Delhi Daredevils';
        update matches set winner_team_name = 'KKR' where winner_team_name = 'Kolkata Knight Riders';

        update matches set loser_team_name = 'CSK' where loser_team_name = 'Chennai Super Kings';
        update matches set loser_team_name = 'SRH' where loser_team_name = 'Sunrisers Hyderabad';
        update matches set loser_team_name = 'LSG' where loser_team_name = 'Lucknow Super Giants';
        update matches set loser_team_name = 'RR' where loser_team_name = 'Rajasthan Royals';
        update matches set loser_team_name = 'PBKS' where loser_team_name = 'Punjab Kings';
        update matches set loser_team_name = 'PBKS' where loser_team_name = 'Kings XI Punjab';
        update matches set loser_team_name = 'RCB' where loser_team_name = 'Royal Challengers Bengaluru';
        update matches set loser_team_name = 'RCB' where loser_team_name = 'Royal Challengers Bangalore';
        update matches set loser_team_name = 'GT' where loser_team_name = 'Gujarat Titans';
        update matches set loser_team_name = 'MI' where loser_team_name = 'Mumbai Indians';
        update matches set loser_team_name = 'DC' where loser_team_name = 'Delhi Capitals';
        update matches set loser_team_name = 'DC' where loser_team_name = 'Delhi Daredevils';
        update matches set loser_team_name = 'KKR' where loser_team_name = 'Kolkata Knight Riders';

        update matches set team_1_team_name = 'CSK' where team_1_team_name = 'Chennai Super Kings';
        update matches set team_1_team_name = 'SRH' where team_1_team_name = 'Sunrisers Hyderabad';
        update matches set team_1_team_name = 'LSG' where team_1_team_name = 'Lucknow Super Giants';
        update matches set team_1_team_name = 'RR' where team_1_team_name = 'Rajasthan Royals';
        update matches set team_1_team_name = 'PBKS' where team_1_team_name = 'Punjab Kings';
        update matches set team_1_team_name = 'PBKS' where team_1_team_name = 'Kings XI Punjab';
        update matches set team_1_team_name = 'RCB' where team_1_team_name = 'Royal Challengers Bengaluru';
        update matches set team_1_team_name = 'RCB' where team_1_team_name = 'Royal Challengers Bangalore';
        update matches set team_1_team_name = 'GT' where team_1_team_name = 'Gujarat Titans';
        update matches set team_1_team_name = 'MI' where team_1_team_name = 'Mumbai Indians';
        update matches set team_1_team_name = 'DC' where team_1_team_name = 'Delhi Capitals';
        update matches set team_1_team_name = 'DC' where team_1_team_name = 'Delhi Daredevils';
        update matches set team_1_team_name = 'KKR' where team_1_team_name = 'Kolkata Knight Riders';


        update matches set team_2_team_name = 'CSK' where team_2_team_name = 'Chennai Super Kings';
        update matches set team_2_team_name = 'SRH' where team_2_team_name = 'Sunrisers Hyderabad';
        update matches set team_2_team_name = 'LSG' where team_2_team_name = 'Lucknow Super Giants';
        update matches set team_2_team_name = 'RR' where team_2_team_name = 'Rajasthan Royals';
        update matches set team_2_team_name = 'PBKS' where team_2_team_name = 'Punjab Kings';
        update matches set team_2_team_name = 'PBKS' where team_2_team_name = 'Kings XI Punjab';
        update matches set team_2_team_name = 'RCB' where team_2_team_name = 'Royal Challengers Bengaluru';
        update matches set team_2_team_name = 'RCB' where team_2_team_name = 'Royal Challengers Bangalore';
        update matches set team_2_team_name = 'GT' where team_2_team_name = 'Gujarat Titans';
        update matches set team_2_team_name = 'MI' where team_2_team_name = 'Mumbai Indians';
        update matches set team_2_team_name = 'DC' where team_2_team_name = 'Delhi Capitals';
        update matches set team_2_team_name = 'DC' where team_2_team_name = 'Delhi Daredevils';
        update matches set team_2_team_name = 'KKR' where team_2_team_name = 'Kolkata Knight Riders';

        update ipl_squads set team_name = 'CSK' where team_name = 'chennai-super-kings';
        update ipl_squads set team_name = 'SRH' where team_name = 'sunrisers-hyderabad';
        update ipl_squads set team_name = 'LSG' where team_name = 'lucknow-super-giants';
        update ipl_squads set team_name = 'RR' where team_name = 'rajasthan-royals';
        update ipl_squads set team_name = 'PBKS' where team_name = 'punjab-kings';
        update ipl_squads set team_name = 'RCB' where team_name = 'royal-challengers-bengaluru';
        update ipl_squads set team_name = 'GT' where team_name = 'gujarat-titans';
        update ipl_squads set team_name = 'MI' where team_name = 'mumbai-indians';
        update ipl_squads set team_name = 'DC' where team_name = 'delhi-capitals';
        update ipl_squads set team_name = 'KKR' where team_name = 'kolkata-knight-riders';